#include "..//game.h"

// COMPILE WITH LOCAL WINDOWS DEBUGGER
// BECAUSE THE GAME IS NOT OPTIMIZED YET FOR NON-DEBUG MODES AS SFML IS CONFIGURED TO RUN IN DEBUG MODE
// BY MATTEO VARGAS QUESADA - 2023
// TRABAJO HONESTO - UNO - AL MENOS NO ES UN TRANSCRIPT DIRECTO DE CHAT GPT COMO MUCHOS OTROS PROYECTOS ;)
    
int main() {

    // CREATE THE WINDOW AND SET THE FRAME RATE LIMIT TO 60 FPS IN ORDER TO SAVE RESOURCES
    sf::RenderWindow window(sf::VideoMode(1280, 720), "UNO Alpha 1.5.9");
    window.setFramerateLimit(15);

    // CREATE THE GAME OBJECT
    Game game;

    // RUN THE GAME LOOP BY CALLING THE RUN FUNCTION
    game.run(window);

    return 0;
}
